version: "2.4"
services:

  mysql:
    image: mysql/mysql-server
    container_name: mysqldb
    networks:
      - ppmtool
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=ppm
      - MYSQL_USER=simran
      - MYSQL_PASSWORD=password
    volumes:
      - mysql_data_volume:/var/lib/mysql
    ports:
      - "9001:3306"
  react:
    image: react_client
    container_name: client
    ports:
      - "3000:3000"
    networks:
      - ppmtool
    depends_on:
      - spring
    command: npm start
  spring:
    image: spring_server
    container_name: server
    ports:
      - "8080:8080"
    environment:
      SPRING_DATASOURCE_URL: "jdbc:mysql://mysqldb:3306/ppm?allowPublicKeyRetrieval=true&useSSL=false&createDatabaseIfNotExist=true"
    networks:
      - ppmtool
    depends_on:
      mysql:
        condition: service_healthy
    command: java -jar ppmtool-0.0.1-SNAPSHOT.jar


networks:
  ppmtool:

volumes:
  mysql_data_volume:
