---
- name: Deploying the application
  hosts: all
  become: true
  tasks:
    - name: Add Docker GPG apt Key
      apt_key:
        url: https://download.docker.com/linux/ubuntu/gpg
        state: present

    - name: Add Docker Repository
      apt_repository:
        repo: deb https://download.docker.com/linux/ubuntu focal stable
        state: present

    - name: Update apt and install docker-ce
      apt:
        name: docker-ce
        state: latest
        update_cache: true

    - name: Install Docker Module for Python
      pip:
        name: docker

    - name: Install docker-compose
      remote_user: ubuntu
      get_url:
        url: https://github.com/docker/compose/releases/download/1.25.1-rc1/docker-compose-Linux-x86_64
        dest: /usr/local/bin/docker-compose
        mode: "u+x,g+x"

    - name: Starting the docker service
      service:
        name: docker
        state: started

    - name: Copying the docker compose file
      copy:
        src: ./docker-compose.yml
        dest: ./

    #    - name: cleaning the docker compose workspace in the local system
    #      shell: docker-compose down

    - name: Starting the application
      shell: docker-compose up -d
